#!/bin/bash
set -e
export GOPATH="$PWD/$(dirname ""$(which """"$0"""")"")"
export PATH="$PATH:$GOPATH/bin"
make --always-make bin/distributed > /dev/null || make --always-make bin/distributed
bin/distributed $*
