#!/bin/bash
set -e
export GOPATH="$PWD/$(dirname ""$(which """"$0"""")"")"
export PATH="$PATH:$GOPATH/bin"
export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig # XXX: only correct for OS X Homebrew users
make --always-make bin/distributedgtk > /dev/null || make --always-make bin/distributedgtk
bin/distributedgtk $*
