#!/bin/bash
set -e
export GOPATH="$PWD/$(dirname ""$(which """"$0"""")"")"
export PATH="$PATH:$GOPATH/bin"
python -m webbrowser http://localhost:6060/pkg/github.com/jeremybanks/go-distributed/
godoc -http=:6060 -index -play=true -q=true -index_throttle=0.25
