#!/bin/bash
set -e
NAME="$(basename ""$0"")"
export GOPATH="$PWD/$(dirname ""$(which """"$0"""")"")"
make --always-make bin/"$NAME" > /dev/null || make --always-make bin/"$NAME"
"$GOPATH/bin/$NAME" $*
