#!/bin/bash
set -e
export GOPATH="$PWD/$(dirname ""$(which """"$0"""")"")"
export PATH="$PATH:$GOPATH/bin"
make --always-make bin/jbitor-create > /dev/null || make --always-make bin/jbitor-create

jbitor-create $*
