#!/bin/bash
set -e

export GOPATH="$PWD/$(dirname ""$(which """"$0"""")"")"
export PATH="$PATH:$GOPATH/bin"

echo "Formatting..."
go fmt bitbucket.com/jeremybanks/go-distributed/bencoding
go fmt bitbucket.com/jeremybanks/go-distributed/main

echo
echo "Testing..."
go test -run=. -bench=NONE bitbucket.com/jeremybanks/go-distributed/bencoding

echo
echo "Installing to ./bin/..."

go install bitbucket.com/jeremybanks/go-distributed/main

echo
echo "Running..."

main $*

echo
