#!/bin/bash
set -e

export GOPATH="$PWD/$(dirname ""$(which """"$0"""")"")"
export PATH="$PATH:$GOPATH/bin"

go fmt bitbucket.com/jeremybanks/go-distributed/bencoding
go fmt bitbucket.com/jeremybanks/go-distributed/main

go test bitbucket.com/jeremybanks/go-distributed/bencoding

go install bitbucket.com/jeremybanks/go-distributed/main

main $*
